### ISSUE TITLE
Can you give me unity project for android, where this plugin is work

### ISSUE THREAD

**Issue by ashot11997** [IanPhilips/UnityOculusAndroidVRBrowser#21]
hello. i am trying to download this from github then build for Oculus Quest, but browser is not working. can you send me pls another unity  project where this is working?

**Comment by ashot11997** [comment]
If you want i can send my project, where this is not working

**Comment by IanPhilips** [comment]
What errors are you getting?

**Comment by ashot11997** [comment]
dont have any error, all is working but website inside browser not showing, i will send my project

**Comment by ashot11997** [comment]
https://github.com/ashot11997/QuestBrowser

**Comment by IanPhilips** [comment]
Lol, I'm not going to debug your project, sorry. YOU have to hunt for
errors so I can advise you on how best to resolve them. Are you building on
a VR device? The browser doesn't work in the editor. What device are you
building on?

**Comment by ashot11997** [comment]
I am building for oculus quest. Not showing nothing inside browser. Also not any error

**Comment by IanPhilips** [comment]
You'll want to find an error or clue as to why it's not working, otherwise
I can't help you.

**Comment by ashot11997** [comment]
But there Is not a error. Can you send me another empty project for Android platform where you installed only your plugin?

**Comment by IanPhilips** [comment]
I don't have a quest to test this on but it works on an Oculus Go so I'm going to close this until someone else reports a problem. Feel free to reopen if you find a clue or error

**Comment by IanPhilips** [comment]
Probably fixed by #24
