### ISSUE TITLE
Crash after Unity logo in Oculus Quest

### ISSUE THREAD

**Issue by sienori** [IanPhilips/UnityOculusAndroidVRBrowser#23]
## Short description
I want to run the OverlayBrowserDemo on Oculus Quest 2.
But the app crashes after the Unity logo is displayed.

## Steps to reproduce
1. Clone this repository and open the `UnityProject` in Unity
2. Set `Build Settings` > `Platform` to `Android`
3. Set `Build Settings` > `Texture Compression` to `ASTC`
4. Click `Switch Platform`
5. Uncheck `Player Settings` > `Player` > `Other Settings` > `Auto Graphics API`
6. Check `Project Settings` > `XR Plug-in Management` > `Plug-in Providers` > `Oculus`
7. Add `Scenes/OverlayBrowserDemo` to `Build Settings` > `Scenes In Build`
8. Install `Android Logcat` in `Package Manager` (To see Quest's log)
9. Build And Run

## Expected result
The app launches in the Quest and I'll be able to see the browser.

## Actual result
The app crashes and exits after the Unity logo is displayed.
Logcat shows the error log: [log.txt](https://github.com/IanPhilips/UnityOculusAndroidVRBrowser/files/5560064/com.ianphilips.UnityAndroidVRBrowser-logcat.txt)

## Additional context
- I updated the Oculus Integration but it did not help
- Disabling `OverlayBrowserView` will launch the app without crashing

## Platform information
OS: Windows 10
HMD: Oculus Quest 2
Unity: 2019.4.14f1

**Comment by sienori** [comment]
I have solved this issue.
I repraced `UnityProject/Assets/Plugin/Android/geckoview-armeabi-v7a-70.0.20191022130254.aar` with `geckoview-armeabi-v7a-80.0.20200818235255.aar`([download here](https://maven.mozilla.org/maven2/?prefix=maven2/org/mozilla/geckoview/geckoview-armeabi-v7a/80.0.20200818235255/)) and it works fine!

**Comment by IanPhilips** [comment]
Ohhh shoot that was my fault, I updated the plugin to work with the geckoview v80 library but didn't replace the geckoview library in the plugin directory! Thanks for figuring that out, if you want to submit a PR to update that you're welcome to or I'll get around to it in the next couple days.

**Comment by IanPhilips** [comment]
Weird how it worked on the Oculus Go after I updated the plugin and tested it...

**Comment by sienori** [comment]
Thank you for the awesome project!
