### ISSUE TITLE
This is not issue. just question. How to connect canvas ui keyboard to webpage inside browser

### ISSUE THREAD

**Issue by ashot11997** [IanPhilips/UnityOculusAndroidVRBrowser#26]
Hi.
How to connect canvas ui keyboard to webpage inside browser.
for example keyboard for google search field.

**Comment by IanPhilips** [comment]
Make your keys pass their key to the following method:
https://github.com/IanPhilips/UnityOculusAndroidVRBrowser/blob/9498c229e244a35a4f4b376dab1840f5bef49596/UnityProject/Assets/Scripts/BrowserView.cs#L63
