### ISSUE TITLE
Donation Link? 

### ISSUE THREAD

**Issue by onkoe** [IanPhilips/UnityOculusAndroidVRBrowser#30]
Hey, this isn't really too related to this project, but do you have a donation link? This is exactly what I've been looking for, and I seriously want to thank you for doing the hard work for me! :)

**Comment by IanPhilips** [comment]
Hey Onkoe, what a heartwarming question! I could post an ETH address easily, do you use crypto? I'll look into a USD link as well

**Comment by IanPhilips** [comment]
Added a paypal link too, thanks!
