### ISSUE TITLE
Contact details for VR collaboration

### ISSUE THREAD

**Issue by blasco** [IanPhilips/UnityOculusAndroidVRBrowser#31]
I see in your readme that you are currently not working on VR. Would you be interested in a VR development position? I cannot find your contact details. Could you contact me so we can continue this conversation? 

Best regards,
Juan

**Comment by IanPhilips** [comment]
Hi Juan, I'm not on the market right now, but I'll let you know if I've any extra time in the future for some collaborating!

Cheers,
Ian
