### ISSUE TITLE
Change Browser View Resolution

### ISSUE THREAD

**Issue by bdelo** [IanPhilips/UnityOculusAndroidVRBrowser#32]
Sorry if this is a dumb question, but I'm a complete noob with unity. Is it possible to change the resolution of the browser view and the web page rendered? In the demo project I've tried changing the height/width of the browserview component to 2560x1440, as well as the height and width of the ovr overlay external surface, but the webpage still renders as if the resolution is extremely small.  Thanks

**Comment by JimothyMarmalade** [comment]
Did you manage to accomplish this? How did you do it?
