### ISSUE TITLE
Browser View content not showing anything

### ISSUE THREAD

**Issue by thapap0** [IanPhilips/UnityOculusAndroidVRBrowser#33]
Hi, 

I'd like to say that this is a great idea and it's something that I've been needing for a project that I'm currently working on, 

but however, I've been running the demo scenes and for some reason, it's not showing any content it the BrowserView window?

I'm a beginner, and not very experienced with programming or Unity, it may just be because I'm new to all this and I'm making a simple error. 

Could you be able to help me out? 

Thanks.

**Comment by IanPhilips** [comment]
Have you been building on an android device? This plugin only works on android - it doesn't work in the editor.
