### ISSUE TITLE
build stop with 'ArgumentException: The Assembly UnityEditor is referenced by UniRx.Async'

### ISSUE THREAD

**Issue by pokkii0206** [IanPhilips/UnityOculusAndroidVRBrowser#34]
Hi, I'm a beginner at unity.
I imported UnityOculusAndroidVRBrowser and fixed the conflict with my default oculus plugin.
But when I build it, stoped with 'ArgumentException: The Assembly UnityEditor is referenced by UniRx.Async'.
Detail is here,

> ArgumentException: The Assembly UnityEditor is referenced by UniRx.Async ('Assets/UnityOculusAndroidVRBrowser-master/UnityProject/obj/Debug/UniRx.Async.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at /Users/bokken/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:154)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at /Users/bokken/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:194)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

Please tell me how to fix this.
Thank you.

**Comment by IanPhilips** [comment]
I don't think we use that library, are you sure it's related to this project? Did you recently try and add UniRx to your project?
