### ISSUE TITLE
Problem building plugin with newer GeckoView Version

### ISSUE THREAD

**Issue by Stormbreaker919** [IanPhilips/UnityOculusAndroidVRBrowser#40]
Hello everyone,

When bulding the GeckoView plugin with the newest version ("95.0.20211129150630"), several errors occur and it is no longer possible to build the plugin.
The erros are:
![grafik](https://user-images.githubusercontent.com/23379219/144108348-fb0ebb6a-e661-40f2-a68d-63348056684c.png)

Any help in solving them would be much appreciated!

P.S.: My plan ist to get the plugin running with the newest version of gecko und eventually on arm64.

**Comment by IanPhilips** [comment]
Whenever you update a major geckoview version you'll have to fix the inevitable API breaking changes. How you fix those errors is not predetermined and your best bet is first understanding what changed and why, then trial and error to fix them.

**Comment by IanPhilips** [comment]
what are the benefits from the newer geckoversion?

**Comment by Stormbreaker919** [comment]
Thanks for the reply. I just wanted to make the plugin more future proof

**Comment by IanPhilips** [comment]
Nice, any luck fixing the errors or stuck on something in particular?

**Comment by jiulengjing** [comment]
i found that the jdk was changed and the GeckoAPI changed also. Maybe we should update all things for code running, incloud the webview.cs code.

**Comment by IanPhilips** [comment]
@Stormbreaker919 @jiulengjing if ya'll could try out the pull request version I'd appreciate it. Updated gecko engine to the latest version.

**Comment by Stormbreaker919** [comment]
Sorry, that i have not answered in some time. In the meantime I decided to use another solution for my master thesis project.
Nevertheless I will try out your pull request when I find the time, to support your cool browser!
