### ISSUE TITLE
Website not displaying

### ISSUE THREAD

**Issue by TheKing349** [IanPhilips/UnityOculusAndroidVRBrowser#44]
Hey! I have downloaded the latest source code and even the beta builds, and no matter what I try, nothing appears on the Quad. The website never shows up on the Quad. Any way to get this to work?

**Comment by IanPhilips** [comment]
What platform are you running it on?

**Comment by IanPhilips** [comment]
It only runs on an oculus headset, not the unity editor

**Comment by TheKing349** [comment]
I’m using the Oculus headset and built the .APK and sideloaded it, and it will still only show a white Quad, won’t load the website

**Comment by TheKing349** [comment]
> It only runs on an oculus headset, not the unity editor

I’m using the Oculus headset and built the .APK and sideloaded it, and it will still only show a white Quad, won’t load the website

**Comment by TheKing349** [comment]
Hey so I was working on my project LATE last night, I had thought I built it and tried it standalone on my Quest, but turns out I didnt. I'm sorry to raise an unneeded alarm for you, but thanks anyways for helping me!
