### ISSUE TITLE
No listener for GeckoView:ContentPermission

### ISSUE THREAD

**Issue by luizcarlosfx** [IanPhilips/UnityOculusAndroidVRBrowser#45]
I'm getting this error "No listener for GeckoView:ContentPermission" whenever I click in the page, then the app crashes

**Comment by luizcarlosfx** [comment]
2022/07/21 15:18:57.893 30782 30912 Error GeckoConsole [JavaScript Error: "Permission error: No listener for GeckoView:ContentPermission" {file: "resource://gre/modules/GeckoViewPermission.jsm" line: 272}]
2022/07/21 15:18:57.893 30782 30912 Error GeckoConsole prompt/<@resource://gre/modules/GeckoViewPermission.jsm:272:12

This is the full log

**Comment by IanPhilips** [comment]
Hey just so the next person can figure this out, I'm curious what did you have to do?

**Comment by luizcarlosfx** [comment]
> Hey just so the next person can figure this out, I'm curious what did you have to do?

It was just a missing transform reference in the unity side. It's strange because reading the log it sounds like a native problem.
